---
- hosts: all
  become: True
  gather_facts: False
  tasks:
    - name: Check ssh connection
      local_action:
          shell ssh -o UserKnownHostsFile=/dev/null -o \
          StrictHostKeyChecking=no ubuntu@{{ inventory_hostname }} \
          "echo success"
      register: ssh_enabled
      until: ssh_enabled.rc == 0
      become: False
      retries: 18
      delay: 10

    - name: Set dns resolved.conf
      ansible.builtin.lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: "^DNS="
        line: "DNS={{ dns_servers }}"
      notify:
        - Restart systemd-resolved
  handlers:
    - name: Restart systemd-resolved
      systemd:
        name: systemd-resolved
        state: restarted
